FROM alpine:latest

VOLUME /conf
WORKDIR /conf

COPY build/linux-amd64/* /usr/bin/
COPY example-config.ini /conf/example-config.ini

ENTRYPOINT ["/usr/bin/DroneExternalConfig", "--conf", "/conf/config.ini"]
