kind: pipeline
type: docker
name: devel

steps:
- name: binaries
  image: docker.io/golang:1.15-alpine
  commands:
    - mkdir -p build/linux-amd64 build/linux-arm64
    - GOOS=linux GOARCH=amd64 go build -v -o build/linux-amd64 .
    - GOOS=linux GOARCH=arm64 go build -v -o build/linux-arm64 .

- name: amd64 image
  image: plugins/docker:linux-amd64
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_TOKEN
    dockerfile: ./Dockerfile.linux-arm64
    repo: trslimey/drone-external-config
    tags:
      - linux-amd64-dev
  depends_on:
    - binaries

#- name: arm64 image
#  image: plugins/docker:linux-arm64
#  settings:
#    username:
#      from_secret: DOCKER_USER
#    password:
#      from_secret: DOCKER_TOKEN
#    dockerfile: ./Dockerfile.linux-arm64
#    repo: trslimey/drone-external-config
#    tags:
#      - linux-arm64-dev
#  depends_on:
#    - binaries

- name: devel docker manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_TOKEN
    target: trslimey/drone-external-config:latest-dev
    template: trslimey/drone-external-config:OS-ARCH-dev
    platforms:
      - linux/amd64
      - linux/arm64
    ignore_missing: true
  depends_on:
    - amd64 image

trigger:
  event:
  - push

---
kind: pipeline
type: docker
name: prod

steps:
- name: prod docker manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_TOKEN
    target: trslimey/drone-external-config:latest
    template: trslimey/drone-external-config:OS-ARCH-dev
    platforms:
      - linux/amd64
      - linux/arm64
    ignore_missing: true

trigger:
  event:
  - promote
  target:
  - production